const UPDATE_CONTACTS_LIST = 'UPDATE_CONTACTS_LIST';
const UPDATE_ACTIVE_CHAT_THREAD = 'UPDATE_ACTIVE_CHAT_THREAD';
const PUSH_MESSAGE_TO_ACTIVE_THREAD = 'PUSH_MESSAGE_TO_ACTIVE_THREAD';
const UPDATE_DRAFT_MESSAGE = 'UPDATE_DRAFT_MESSAGE';

export {
    UPDATE_CONTACTS_LIST,
    UPDATE_ACTIVE_CHAT_THREAD,
    PUSH_MESSAGE_TO_ACTIVE_THREAD,
    UPDATE_DRAFT_MESSAGE
}